/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.packages.view;

import my.packages.Empresa;
import my.packages.ProjectED;
import my.packages.utilities.DBconnection;
/**
 *
 * @author rhino
 */
public class initB extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private DBconnection connection;
    private Empresa empresa;
    private init inicio;
    
    public initB(Empresa empresa, DBconnection connection) {
        initComponents();
        this.empresa = empresa;
        this.connection = connection;
        inicio = new init(empresa, connection);
        setLocationRelativeTo(null);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        login = new javax.swing.JButton();
        UNTIQUETE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Comprobar Base");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 130, 50));

        login.setText("Avanzar");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 140, 50));

        UNTIQUETE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        UNTIQUETE.setForeground(new java.awt.Color(255, 0, 0));
        UNTIQUETE.setText("UNTIQUETE");
        jPanel1.add(UNTIQUETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 150, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 250, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 435, 282));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(connection.createDB())
            jLabel1.setText("Creada la base de datos.");
        else
            jLabel1.setText("Base de datos funcional.");
    }//GEN-LAST:event_jButton1MouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
              inicio.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UNTIQUETE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    // End of variables declaration//GEN-END:variables
}
