/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.packages.view;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import my.packages.Empresa;
import my.packages.Usuario;
import my.packages.utilities.DBconnection;

/**
 *
 * @author rhino
 */
public class perfilUsuario extends javax.swing.JFrame {

    /**
     * Creates new form perfilUsuario
     */
    private Empresa empresa;
    private DBconnection connection;
    private JFrame jframe;
    private String user1;
    private Usuario usuario;
    private String[] info = new String[11];
    private String datos[][];
    private int iRow, iCol;
    public perfilUsuario(Empresa empresa, DBconnection connection, JFrame jframe, String user, Usuario usuario) {
        this.empresa = empresa;
        this.connection = connection;
        this.jframe = jframe;
        this.user1 = user;
        this.usuario = usuario;
        initComponents();
        fill();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        genero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ciudad = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        events = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        events1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        UNTIQUETE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numid.setEditable(false);
        numid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numidActionPerformed(evt);
            }
        });
        jPanel1.add(numid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 140, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Correo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));
        jPanel1.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 140, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Ciudad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 140, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Numero");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));
        jPanel1.add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 140, -1));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Edad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 140, -1));
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 140, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jPanel1.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        user.setEditable(false);
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 140, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Apellidos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 140, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("NumeroID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        events.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        events.setText("Eventos comprados");
        jPanel1.add(events, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        id.setEditable(false);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 140, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Genero");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setText("Volver");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 130, 40));

        jButton6.setBackground(new java.awt.Color(153, 255, 153));
        jButton6.setText("Actualizar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 130, 40));

        events1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        events1.setText("Reservas");
        jPanel1.add(events1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        String datos[][] = new String[usuario.getComprados().size()+10][3];
        for(int i=0;i<usuario.getComprados().size();i++){
            datos[i][0] = usuario.getComprados().get(i).getNombre();
            datos[i][1] = usuario.getComprados().get(i).getLugar().getNombre();
            datos[i][2] = usuario.getComprados().get(i).getDate().toString();
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            datos,
            new String [] {
                "Nombre", "Lugar", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 240, 220));

        String datos1[][] = new String[usuario.getReservados().size()+10][3];
        for(int i=0;i<usuario.getReservados().size();i++){
            datos1[i][0] = usuario.getReservados().get(i).getNombre();
            datos1[i][1] = usuario.getReservados().get(i).getLugar().getNombre();
            datos1[i][2] = usuario.getReservados().get(i).getDate().toString();
        }
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            datos1,
            new String [] {
                "Nombre", "Lugar", "Fecha"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 240, 220));

        jButton7.setBackground(new java.awt.Color(255, 51, 51));
        jButton7.setText("Cancelar Reserva");
        jButton7.setEnabled(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 140, 40));

        UNTIQUETE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        UNTIQUETE.setForeground(new java.awt.Color(255, 0, 0));
        UNTIQUETE.setText("UNTIQUETE");
        jPanel1.add(UNTIQUETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 150, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numidActionPerformed

    private void fill(){
        ArrayList<String> usuario = connection.selectInfo(user1);
        int i = 0;
        for (String dato : usuario) {
            info[i] = dato;
            //System.out.println(info[i]);
            ++i;
            
        }
        this.user1 = info[3];
        nombre.setText(info[0]);
        apellido.setText(info[1]);
        edad.setText(info[2]);
        user.setText(info[3]);
        pass.setText(info[4]);
        id.setText(info[5]);
        numid.setText(info[6]);
        genero.setText(info[7]);
        correo.setText(info[8]);
        ciudad.setText(info[9]);
        number.setText(info[10]);
    }
    
    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        new inicioUsuario(empresa, connection, user1, usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        for (String string : info) {
            System.out.println(string);
        }
        String[] temp = new String[11];
        
        temp[0] = nombre.getText();
        temp[1] = apellido.getText();
        temp[2] = edad.getText();
        temp[3]= user.getText();
        temp[4] = pass.getText();
        temp[5] = id.getText();
        temp[6] = numid.getText();
        temp[7] = genero.getText();
        temp[8] = correo.getText();
        temp[9] = ciudad.getText();
        temp[10] = number.getText();
        
        
        if(empresa.getConnection().updateUsuario(temp, info[3])){
            System.out.println("Actualizado");
            this.fill();
        }else{
            System.out.println("No actualizado");
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        if(jTable2.getValueAt(iRow, 0) != null){
            String evento = jTable2.getValueAt(iRow, 0).toString();
            empresa.cancelarReserva(usuario, evento);
            DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
            modelo.removeRow(iRow);
            jTable2.setModel(modelo);
            new CancelarExitoso().setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        jButton7.setEnabled(true);
        iRow = jTable2.getSelectedRow();
    }//GEN-LAST:event_jTable2MouseClicked

    public String getUser1() {
        return user1;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UNTIQUETE;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField edad;
    private javax.swing.JLabel events;
    private javax.swing.JLabel events1;
    private javax.swing.JTextField genero;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField number;
    private javax.swing.JTextField numid;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
